import { useEffect, useState } from 'react'
import { api } from '../api/client'

export default function AssistantModal({ onClose }) {
  const [message,setMessage]=useState(''),[messages,setMessages]=useState([]),[busy,setBusy]=useState(false),[configured,setConfigured]=useState(null),[error,setError]=useState('')
  useEffect(()=>{api.getAssistantStatus().then(r=>setConfigured(r.configured)).catch(()=>setConfigured(false))},[])
  const send=async e=>{e.preventDefault();const text=message.trim();if(!text||busy)return;setMessages(x=>[...x,{role:'user',content:text}]);setMessage('');setBusy(true);setError('');try{const context={page:location.pathname, timestamp:new Date().toISOString()};const r=await api.groqChat({message:text,context});setMessages(x=>[...x,{role:'assistant',content:r.answer,model:r.model}])}catch(err){setError(err.message)}finally{setBusy(false)}}
  return <div style={{position:'fixed',inset:0,zIndex:3500,background:'rgba(0,0,0,.72)',display:'grid',placeItems:'center',padding:16}} onClick={e=>e.target===e.currentTarget&&onClose()}><section style={{width:'min(820px,96vw)',height:'min(680px,88vh)',display:'flex',flexDirection:'column',background:'var(--surface)',border:'1px solid var(--border)',borderRadius:10,overflow:'hidden'}}><header style={{display:'flex',alignItems:'center',gap:10,padding:'12px 14px',borderBottom:'1px solid var(--border)'}}><b>Sentinel Operations Assistant</b><span style={{fontSize:10,color:configured?'var(--green)':'var(--text2)'}}>{configured===null?'Checking…':configured?'Connected':'Not configured'}</span><button onClick={onClose} style={{marginLeft:'auto',border:0,background:'transparent',color:'var(--text)',fontSize:18,cursor:'pointer'}}>×</button></header><div style={{flex:1,overflow:'auto',padding:14}}>{!messages.length&&<div style={{color:'var(--text2)',fontSize:12,lineHeight:1.6}}>Ask about camera operations, alerts, investigations, journeys or supplied operational context. The assistant does not execute actions and does not invent system data.</div>}{messages.map((m,i)=><div key={i} style={{marginBottom:12,textAlign:m.role==='user'?'right':'left'}}><div style={{display:'inline-block',maxWidth:'85%',padding:'9px 11px',borderRadius:8,background:m.role==='user'?'var(--surface2)':'rgba(88,166,255,.08)',border:'1px solid var(--border)',fontSize:12,whiteSpace:'pre-wrap',textAlign:'left'}}>{m.content}{m.model&&<div style={{marginTop:5,fontSize:9,color:'var(--text2)'}}>{m.model}</div>}</div></div>)}</div>{error&&<div style={{padding:'6px 14px',color:'var(--red)',fontSize:11}}>{error}</div>}<form onSubmit={send} style={{display:'flex',gap:8,padding:10,borderTop:'1px solid var(--border)'}}><input value={message} onChange={e=>setMessage(e.target.value)} placeholder={configured===false?'Configure GROQ_API_KEY to use the assistant':'Ask Sentinel…'} disabled={configured===false||busy} style={{flex:1,padding:'9px 10px',borderRadius:6,border:'1px solid var(--border)',background:'var(--surface2)',color:'var(--text)'}}/><button disabled={!message.trim()||busy||configured===false} style={{padding:'9px 14px',border:0,borderRadius:6,background:'var(--accent)',color:'#fff',cursor:'pointer'}}>{busy?'Sending…':'Send'}</button></form></section></div>
}
