import { useEffect,useRef,useState } from 'react'
import L from 'leaflet'
import 'leaflet/dist/leaflet.css'
import { api } from '../api/client'
import { Button } from './ui/button'

const BOUNDS=L.latLngBounds([20.08,68.08],[24.55,74.55]),KEY='sentinel.registry.map.session.v1'
const PIN=L.divIcon({className:'sentinel-registry-pin',iconSize:[34,42],iconAnchor:[17,42],html:'<div style="width:32px;height:32px;border-radius:50% 50% 50% 0;background:#f97316;border:3px solid #fff;transform:rotate(-45deg);box-shadow:0 4px 14px rgba(0,0,0,.7)"><span style="display:block;width:9px;height:9px;border-radius:50%;background:#090705;margin:8px auto"></span></div>'})
const EMPTY={name:'',stream_id:'',location:'',department:'',owner_organization:'',rtsp_url:'',hls_url:'',lat:'',lng:'',vendor_id:'',model_id:''}
const FIELDS=[['name','Camera name',true],['stream_id','Stream ID',true],['location','Location'],['department','Department'],['owner_organization','Owner'],['rtsp_url','RTSP URL'],['hls_url','HLS URL'],['lat','Latitude'],['lng','Longitude']]

export default function CameraRegistryModal({onClose,onSaved,onImport}){
 const[mode,setMode]=useState('choice'),[form,setForm]=useState(EMPTY),[file,setFile]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[result,setResult]=useState(null),[vendors,setVendors]=useState([]),[models,setModels]=useState([])
 const node=useRef(null),map=useRef(null),marker=useRef(null)
 useEffect(()=>{api.getVendors().then(setVendors).catch(()=>setVendors([]))},[])
 useEffect(()=>{if(!form.vendor_id){setModels([]);return}api.getVendorModels(form.vendor_id).then(setModels).catch(()=>setModels([]))},[form.vendor_id])
 useEffect(()=>{if(mode!=='manual'||!node.current)return;let saved=null;try{saved=JSON.parse(sessionStorage.getItem(KEY)||'null')}catch{};const m=L.map(node.current,{zoomControl:true,maxBounds:BOUNDS.pad(.55),maxBoundsViscosity:.8});L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'OpenStreetMap contributors'}).addTo(m);if(saved?.center&&Number.isFinite(Number(saved.zoom)))m.setView(saved.center,Number(saved.zoom),{animate:false});else m.fitBounds(BOUNDS,{animate:false});m.on('click',e=>setCoords(e.latlng.lat,e.latlng.lng));m.on('moveend',()=>{const c=m.getCenter();sessionStorage.setItem(KEY,JSON.stringify({center:[c.lat,c.lng],zoom:m.getZoom()}))});map.current=m;requestAnimationFrame(()=>m.invalidateSize());return()=>{m.remove();map.current=null;marker.current=null}},[mode])
 const setCoords=(lat,lng)=>setForm(v=>({...v,lat:Number(lat).toFixed(6),lng:Number(lng).toFixed(6)}))
 useEffect(()=>{if(mode!=='manual'||!map.current)return;const lat=Number(form.lat),lng=Number(form.lng);if(!Number.isFinite(lat)||!Number.isFinite(lng))return;if(!marker.current){marker.current=L.marker([lat,lng],{draggable:true,icon:PIN,title:'Camera location'}).addTo(map.current);marker.current.on('dragend',e=>{const p=e.target.getLatLng();setCoords(p.lat,p.lng)})}else marker.current.setLatLng([lat,lng]);map.current.panTo([lat,lng])},[mode,form.lat,form.lng])
 const change=e=>setForm(v=>({...v,[e.target.name]:e.target.value}))
 const reset=()=>{setMode('choice');setFile(null);setResult(null);setError('');setForm(EMPTY)}
 const submit=async e=>{e.preventDefault();setBusy(true);setError('');try{await onSaved({...form,stream_id:Number(form.stream_id),vendor_id:form.vendor_id||undefined,model_id:form.model_id||undefined,lat:form.lat===''?undefined:Number(form.lat),lng:form.lng===''?undefined:Number(form.lng),coord_source:form.lat&&form.lng?'manual':'unknown',coord_confidence:form.lat&&form.lng?1:undefined});onClose()}catch(err){setError(err.message||'Unable to register camera')}finally{setBusy(false)}}
 const importRegistry=async()=>{if(!file)return;setBusy(true);setError('');try{setResult(await onImport(file))}catch(err){setError(err.message||'Unable to import registry')}finally{setBusy(false)}}
 if(mode==='choice')return <div style={overlay}><section style={choiceModal}><header style={header}><div><b>Camera Registry</b><div style={sub}>Choose a registry operation.</div></div><button onClick={onClose} style={close}>×</button></header><main style={choiceGrid}><button onClick={()=>setMode('import')} style={choice}><span style={choiceIcon}>⇩</span><b>Bulk Import</b><small>Import CSV/XLSX registry records with audit validation.</small></button><button onClick={()=>setMode('manual')} style={choice}><span style={choiceIcon}>＋</span><b>Register Camera</b><small>Register one camera and place its exact location on the Gujarat map.</small></button></main><footer style={footer}><Button variant="outline" onClick={onClose}>Close</Button></footer></section></div>
 if(mode==='import')return <div style={overlay}><section style={choiceModal}><header style={header}><div><b>Bulk Import</b><div style={sub}>Import or update multiple cameras.</div></div><button onClick={onClose} style={close}>×</button></header><main style={{padding:20}}><div style={uploadBox}><b>Registry file</b><span>CSV/XLSX · duplicate-safe · coordinate validation · audited import</span><input type="file" accept=".csv,.xlsx,text/csv,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" onChange={e=>setFile(e.target.files?.[0]||null)} style={input}/>{file&&<small style={{color:'var(--text2)'}}>{file.name}</small>}<Button disabled={busy||!file} onClick={importRegistry}>{busy?'Importing…':'Import & Audit'}</Button>{result&&<div style={resultBox}>Imported {result.accepted_rows}/{result.total_rows}; rejected {result.rejected_rows}.</div>}{error&&<div style={errorBox}>{error}</div>}</div></main><footer style={footer}><Button variant="outline" onClick={reset}>Back</Button><Button variant="outline" onClick={onClose}>Close</Button></footer></section></div>
 return <div style={overlay}><form onSubmit={submit} style={modal}><header style={header}><div><b>Register Camera</b><div style={sub}>Single-camera manual registration.</div></div><button type="button" onClick={onClose} style={close}>×</button></header><section style={body}><div style={formPane}>{FIELDS.map(([name,label,required])=><label key={name} style={labelStyle}>{label}{required?' *':''}<input name={name} value={form[name]} required={required} onChange={change} style={input}/></label>)}<label style={labelStyle}>Vendor<select name="vendor_id" value={form.vendor_id} onChange={e=>{change(e);setForm(v=>({...v,model_id:''}))}} style={input}><option value="">Select vendor</option>{vendors.map(v=><option key={v.id} value={v.id}>{v.name}</option>)}</select></label><label style={labelStyle}>Camera model<select name="model_id" value={form.model_id} disabled={!form.vendor_id} onChange={change} style={input}><option value="">Select model</option>{models.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label>{error&&<div style={errorBox}>{error}</div>}</div><div style={mapPane}><div ref={node} style={{position:'absolute',inset:0}}/><div style={mapLabel}>Camera Location</div></div></section><footer style={footer}><Button variant="outline" type="button" onClick={reset}>Back</Button><Button variant="outline" type="button" onClick={onClose}>Cancel</Button><Button type="submit" disabled={busy}>{busy?'Saving…':'Save Camera'}</Button></footer></form></div>
}
const overlay={position:'fixed',inset:0,zIndex:3000,display:'grid',placeItems:'center',padding:14,background:'rgba(0,0,0,.82)'},choiceModal={width:'min(680px,94vw)',background:'var(--surface)',border:'1px solid var(--border)',borderRadius:13,overflow:'hidden',boxShadow:'var(--shadow)'},modal={...choiceModal,width:'min(1040px,96vw)',height:'min(820px,92vh)',display:'flex',flexDirection:'column'},header={display:'flex',alignItems:'center',justifyContent:'space-between',padding:'15px 18px',borderBottom:'1px solid var(--border)'},sub={marginTop:3,color:'var(--text2)',fontSize:11},close={border:0,background:'transparent',color:'var(--text2)',fontSize:22,cursor:'pointer'},choiceGrid={display:'grid',gridTemplateColumns:'repeat(2,minmax(0,1fr))',gap:12,padding:20},choice={minHeight:190,display:'grid',placeItems:'center',alignContent:'center',gap:8,padding:22,borderRadius:12,border:'1px solid var(--border)',background:'var(--surface2)',color:'var(--text)',cursor:'pointer',textAlign:'center'},choiceIcon={width:46,height:46,display:'grid',placeItems:'center',borderRadius:11,background:'var(--accent-soft)',border:'1px solid var(--accent-border)',color:'var(--accent-strong)',fontSize:22,fontWeight:800},uploadBox={display:'grid',gap:11,padding:20,border:'1px dashed var(--accent-border)',borderRadius:11,background:'var(--accent-soft)',color:'var(--text2)'},formPane={padding:17,overflowY:'auto'},mapPane={position:'relative',minHeight:430,background:'#000'},mapLabel={position:'absolute',top:10,left:10,zIndex:500,padding:'6px 9px',borderRadius:7,background:'rgba(0,0,0,.78)',border:'1px solid var(--border-strong)',fontSize:10,color:'var(--text)'},body={display:'grid',gridTemplateColumns:'minmax(310px,.92fr) minmax(420px,1.08fr)',minHeight:0,flex:1},labelStyle={display:'grid',gap:5,marginBottom:11,fontSize:12,color:'var(--text2)'},input={width:'100%',padding:'9px 10px',borderRadius:8,border:'1px solid var(--border)',background:'var(--surface2)',color:'var(--text)',fontSize:13},footer={display:'flex',justifyContent:'flex-end',gap:8,padding:12,borderTop:'1px solid var(--border)',background:'var(--surface)'},errorBox={marginTop:10,padding:9,borderRadius:8,border:'1px solid rgba(248,113,113,.4)',background:'rgba(248,113,113,.08)',color:'var(--red)',fontSize:11},resultBox={padding:9,borderRadius:8,border:'1px solid rgba(74,222,128,.3)',background:'rgba(74,222,128,.06)',color:'var(--green)',fontSize:11}}
