import { useEffect, useRef, useState } from 'react'
import { api } from '../api/client'
import { Input } from './ui/input'

const SearchIcon=()=> <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round"><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></svg>
const LiveIcon=()=> <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M15 10l4.5-2.1A1 1 0 0 1 21 8.8v6.4a1 1 0 0 1-1.5.9L15 14"/><rect x="1" y="6" width="15" height="12" rx="2"/></svg>
const PinIcon=()=> <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M20 10c0 5-8 12-8 12S4 15 4 10a8 8 0 1 1 16 0Z"/><circle cx="12" cy="10" r="2.5"/></svg>

export default function CameraSearch({ value, onChange, onViewCamera, onLocateCamera }) {
  const [open,setOpen]=useState(false),[results,setResults]=useState([]),[loading,setLoading]=useState(false),[error,setError]=useState(''),seq=useRef(0),root=useRef(null)
  useEffect(()=>{const close=e=>{if(root.current&&!root.current.contains(e.target))setOpen(false)};document.addEventListener('mousedown',close);return()=>document.removeEventListener('mousedown',close)},[])
  useEffect(()=>{const q=value.trim();seq.current+=1;const current=seq.current;if(!q){setResults([]);setLoading(false);setError('');return}const controller=new AbortController();const timer=setTimeout(async()=>{setLoading(true);setError('');try{const data=await api.searchCameras(q,{signal:controller.signal});if(current===seq.current)setResults(data.items||[])}catch(err){if(err.name!=='AbortError'&&current===seq.current)setError(err.message||'Search failed')}finally{if(current===seq.current)setLoading(false)}},180);return()=>{clearTimeout(timer);controller.abort()}},[value])
  return <div ref={root} className="sentinel-camera-search" style={{position:'relative',width:'min(460px,40vw)'}}><div style={{position:'relative'}}><span style={{position:'absolute',left:11,top:'50%',transform:'translateY(-50%)',color:'var(--muted)',pointerEvents:'none'}}><SearchIcon/></span><Input value={value} onFocus={()=>value.trim()&&setOpen(true)} onChange={e=>{onChange(e.target.value);setOpen(true)}} placeholder="Search cameras…" aria-label="Search cameras" style={{paddingLeft:34,height:38}}/>{loading&&<span style={{position:'absolute',right:10,top:'50%',transform:'translateY(-50%)',fontSize:9,color:'var(--muted)'}}>Searching…</span>}</div>{open&&value.trim()&&<div style={{position:'absolute',top:'calc(100% + 6px)',left:0,right:0,zIndex:1800,maxHeight:420,overflowY:'auto',background:'#050505',border:'1px solid var(--border)',borderRadius:10,boxShadow:'0 18px 50px rgba(0,0,0,.65)'}}>{error?<div style={{padding:14,color:'var(--high)',fontSize:11}}>{error}</div>:results.length===0&&!loading?<div style={{padding:18,textAlign:'center',color:'var(--text2)',fontSize:11}}>No cameras found</div>:results.map(camera=><div key={camera.id} style={{display:'flex',gap:10,alignItems:'center',padding:'10px 11px',borderBottom:'1px solid var(--border)'}}><div style={{flex:1,minWidth:0}}><div style={{fontSize:11,fontWeight:800}}>{camera.name||`CAM-${camera.stream_id}`}</div><div style={{fontSize:9,color:'var(--text2)',marginTop:3,whiteSpace:'nowrap',overflow:'hidden',textOverflow:'ellipsis'}}>{camera.location||'Location not registered'} · {camera.department||'Unassigned'}</div></div><button title="View live feed" aria-label="View live feed" onClick={()=>{setOpen(false);onViewCamera?.(camera)}} style={{width:30,height:30,display:'grid',placeItems:'center',border:'1px solid var(--accent)',borderRadius:7,background:'var(--accent)',color:'#111',cursor:'pointer'}}><LiveIcon/></button><button title="Locate on map" aria-label="Locate on map" onClick={()=>{setOpen(false);onLocateCamera?.(camera)}} style={{width:30,height:30,display:'grid',placeItems:'center',border:'1px solid var(--border)',borderRadius:7,background:'var(--surface2)',color:'var(--accent)',cursor:'pointer'}}><PinIcon/></button></div>)}</div>}</div>
}
