import { useEffect,useRef,useState } from 'react'
import L from 'leaflet'
import 'leaflet/dist/leaflet.css'
import { api } from '../api/client'
import { Button } from './ui/button'

const BOUNDS=L.latLngBounds([20.08,68.08],[24.55,74.55]),KEY='sentinel.registry.map.session.v1'
const PIN=L.divIcon({className:'sentinel-registry-pin',iconSize:[34,42],iconAnchor:[17,42],html:'<div style="width:32px;height:32px;border-radius:50% 50% 50% 0;background:#f97316;border:3px solid #fff;transform:rotate(-45deg);box-shadow:0 4px 14px rgba(0,0,0,.7)"><span style="display:block;width:9px;height:9px;border-radius:50%;background:#090705;margin:8px auto"></span></div>'})
const EMPTY={name:'',stream_id:'',location:'',department:'',owner_organization:'',rtsp_url:'',hls_url:'',lat:'',lng:'',vendor_id:'',model_id:''}
const FIELDS=[['name','Camera name',true],['stream_id','Stream ID',true],['location','Location'],['department','Department'],['owner_organization','Owner'],['rtsp_url','RTSP URL'],['hls_url','HLS URL'],['lat','Latitude'],['lng','Longitude']]

const qualityTone=q=>q?.status==='ready'?'green':q?.status==='warning'?'amber':'red'
const detailOf=err=>err?.detail?.analysis||err?.detail?.detail?.analysis||null

function QualityPanel({analysis}){
 if(!analysis)return null
 const s=analysis.summary,tone=qualityTone(s), color=tone==='green'?'var(--green)':tone==='amber'?'#f59e0b':'var(--red)'
 const issues=[...(s.header_warnings||[]),...analysis.rows.flatMap(r=>r.issues||[])]
 return <div style={{marginTop:12,border:`1px solid ${color}`,borderRadius:10,overflow:'hidden',background:'var(--surface2)'}}>
   <div style={{display:'flex',alignItems:'center',gap:9,padding:'10px 12px',borderBottom:'1px solid var(--border)'}}><span style={{width:9,height:9,borderRadius:'50%',background:color,boxShadow:`0 0 0 3px ${color}22`}}/><b style={{color,fontSize:12}}>{tone==='green'?'READY — exact registry format':tone==='amber'?'READY WITH WARNINGS':'IMPORT BLOCKED'}</b><span style={{marginLeft:'auto',fontSize:10,color:'var(--text2)'}}>{s.total_rows} rows · {s.ready_rows} clean · {s.warning_rows} warning · {s.blocked_rows} blocked</span></div>
   <div style={{padding:'9px 12px',display:'grid',gap:6,fontSize:10,color:'var(--text2)'}}>{issues.slice(0,30).map((i,n)=><div key={`${i.row||'h'}-${i.field||i.column}-${n}`} style={{display:'grid',gridTemplateColumns:'52px 125px 1fr',gap:7}}><b style={{color:i.severity==='error'?'var(--red)':'#f59e0b'}}>{i.severity?.toUpperCase()}</b><b>{i.row?`Row ${i.row}`:(i.column||'Header')}</b><span>{i.message}</span></div>)}{issues.length>30&&<span>+ {issues.length-30} more issues</span>}</div>
 </div>
}

export default function CameraRegistryModal({onClose,onSaved,onImport}){
 const[mode,setMode]=useState('choice'),[form,setForm]=useState(EMPTY),[file,setFile]=useState(null),[isValidating,setIsValidating]=useState(false),[isImporting,setIsImporting]=useState(false),[error,setError]=useState(''),[result,setResult]=useState(null),[analysis,setAnalysis]=useState(null),[ack,setAck]=useState(false),[vendors,setVendors]=useState([]),[models,setModels]=useState([])
 const node=useRef(null),map=useRef(null),marker=useRef(null)
 const busy=isValidating||isImporting
 useEffect(()=>{api.getVendors().then(setVendors).catch(()=>setVendors([]))},[])
 useEffect(()=>{if(!form.vendor_id){setModels([]);return}api.getVendorModels(form.vendor_id).then(setModels).catch(()=>setModels([]))},[form.vendor_id])
 useEffect(()=>{if(mode!=='manual'||!node.current)return;let saved=null;try{saved=JSON.parse(sessionStorage.getItem(KEY)||'null')}catch{};const m=L.map(node.current,{zoomControl:true,maxBounds:BOUNDS.pad(.55),maxBoundsViscosity:.8});L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'OpenStreetMap contributors'}).addTo(m);if(saved?.center&&Number.isFinite(Number(saved.zoom)))m.setView(saved.center,Number(saved.zoom),{animate:false});else m.fitBounds(BOUNDS,{animate:false});m.on('click',e=>setCoords(e.latlng.lat,e.latlng.lng));m.on('moveend',()=>{const c=m.getCenter();sessionStorage.setItem(KEY,JSON.stringify({center:[c.lat,c.lng],zoom:m.getZoom()}))});map.current=m;requestAnimationFrame(()=>m.invalidateSize());return()=>{m.remove();map.current=null;marker.current=null}},[mode])
 const setCoords=(lat,lng)=>setForm(v=>({...v,lat:Number(lat).toFixed(6),lng:Number(lng).toFixed(6)}))
 useEffect(()=>{if(mode!=='manual'||!map.current)return;const lat=Number(form.lat),lng=Number(form.lng);if(!Number.isFinite(lat)||!Number.isFinite(lng))return;if(!marker.current){marker.current=L.marker([lat,lng],{draggable:true,icon:PIN,title:'Camera location'}).addTo(map.current);marker.current.on('dragend',e=>{const p=e.target.getLatLng();setCoords(p.lat,p.lng)})}else marker.current.setLatLng([lat,lng]);map.current.panTo([lat,lng])},[mode,form.lat,form.lng])
 const change=e=>setForm(v=>({...v,[e.target.name]:e.target.value}))
 const reset=()=>{setMode('choice');setFile(null);setResult(null);setAnalysis(null);setError('');setAck(false);setForm(EMPTY);setIsValidating(false);setIsImporting(false)}
 const selectFile=async e=>{const selected=e.target.files?.[0]||null;setFile(selected);setResult(null);setError('');setAnalysis(null);setAck(false);if(!selected)return;setIsValidating(true);try{setAnalysis(await api.validateCameraImport(selected))}catch(err){setError(err.message||'Unable to analyze registry file')}finally{setIsValidating(false)}}
 const importRegistry=async()=>{if(!file||!analysis)return;setIsImporting(true);setError('');try{const value=onImport?await onImport(file,ack):await api.importCameras(file,ack);setResult(value);setAck(false)}catch(err){const returned=detailOf(err);if(returned){setAnalysis(returned);if(err.status===409)setError('Review the warnings below and acknowledge them to continue.');else setError(err.message)}else setError(err.message||'Unable to import registry')}finally{setIsImporting(false)}}
 const submit=async e=>{e.preventDefault();setIsImporting(true);setError('');try{await onSaved({...form,stream_id:Number(form.stream_id),vendor_id:form.vendor_id||undefined,model_id:form.model_id||undefined,lat:form.lat===''?undefined:Number(form.lat),lng:form.lng===''?undefined:Number(form.lng),coord_source:form.lat&&form.lng?'manual':'unknown',coord_confidence:form.lat&&form.lng?1:undefined});onClose()}catch(err){setError(err.message||'Unable to register camera')}finally{setIsImporting(false)}}
 const canImport=Boolean(file&&analysis?.summary?.allow_upload&&!analysis?.summary?.requires_warning_ack||file&&analysis?.summary?.allow_upload&&analysis?.summary?.requires_warning_ack&&ack)
 if(mode==='choice')return <div style={overlay}><section style={choiceModal}><header style={header}><div><b>Camera Registry</b><div style={sub}>Choose a registry operation.</div></div><button onClick={onClose} style={close}>×</button></header><main style={choiceGrid}><button onClick={()=>setMode('import')} style={choice}><span style={choiceIcon}>⇩</span><b>Bulk Import</b><small>Intelligent CSV/XLSX validation, warnings and audited import.</small></button><button onClick={()=>setMode('manual')} style={choice}><span style={choiceIcon}>＋</span><b>Register Camera</b><small>Register one camera and place its exact location on the Gujarat map.</small></button></main><footer style={footer}><Button variant="outline" onClick={onClose}>Close</Button></footer></section></div>
 if(mode==='import')return <div style={overlay}><section style={{...choiceModal,width:'min(860px,96vw)'}}><header style={header}><div><b>Intelligent Bulk Import</b><div style={sub}>Analyze first · warnings are explainable · errors block unsafe records.</div></div><button onClick={onClose} style={close}>×</button></header><main style={{padding:20,maxHeight:'72vh',overflowY:'auto'}}><div style={uploadBox}><b>Registry file</b><span>CSV/XLSX · stream identity required · coordinates checked · duplicates audited</span><input type="file" accept=".csv,.xlsx,text/csv,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" disabled={busy} onChange={selectFile} style={input}/>{file&&<small style={{color:'var(--text2)'}}>{file.name}</small>}{isValidating&&<div style={{color:'var(--accent)',fontSize:11}}>Validating file…</div>}{isImporting&&!isValidating&&<div style={{color:'var(--accent)',fontSize:11}}>Importing registry…</div>}{analysis&&<QualityPanel analysis={analysis}/>} {analysis?.summary?.requires_warning_ack&&analysis.summary.allow_upload&&<label style={{display:'flex',gap:8,alignItems:'flex-start',padding:'10px 0',fontSize:11,color:'var(--text2)'}}><input type="checkbox" checked={ack} disabled={isImporting} onChange={e=>setAck(e.target.checked)}/><span>I reviewed the warnings and understand that the usable camera data will be imported while the listed non-critical fields are normalized or ignored.</span></label>}{result&&<div style={resultBox}>Imported {result.accepted_rows}/{result.total_rows}; rejected {result.rejected_rows}. Audit record created.</div>}{error&&<div style={errorBox}>{error}</div>}</div></main><footer style={footer}><Button variant="outline" onClick={reset} disabled={busy}>Back</Button><Button variant="outline" onClick={onClose} disabled={busy}>Close</Button><Button disabled={busy||!canImport} onClick={importRegistry}>{isImporting?'Importing…':analysis?.summary?.requires_warning_ack?'Acknowledge & Import':'Check & Import'}</Button></footer></section></div>
 return <div style={overlay}><form onSubmit={submit} style={modal}><header style={header}><div><b>Register Camera</b><div style={sub}>Single-camera manual registration.</div></div><button type="button" onClick={onClose} style={close}>×</button></header><section style={body}><div style={formPane}>{FIELDS.map(([name,label,required])=><label key={name} style={labelStyle}>{label}{required?' *':''}<input name={name} value={form[name]} required={required} onChange={change} disabled={isImporting} style={input}/></label>)}<label style={labelStyle}>Vendor<select name="vendor_id" value={form.vendor_id} disabled={isImporting} onChange={e=>{change(e);setForm(v=>({...v,model_id:''}))}} style={input}><option value="">Select vendor</option>{vendors.map(v=><option key={v.id} value={v.id}>{v.name}</option>)}</select></label><label style={labelStyle}>Camera model<select name="model_id" value={form.model_id} disabled={!form.vendor_id||isImporting} onChange={change} style={input}><option value="">Select model</option>{models.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label>{error&&<div style={errorBox}>{error}</div>}</div><div style={mapPane}><div ref={node} style={{position:'absolute',inset:0}}/><div style={mapLabel}>Camera Location</div></div></section><footer style={footer}><Button variant="outline" type="button" onClick={reset} disabled={isImporting}>Back</Button><Button variant="outline" type="button" onClick={onClose} disabled={isImporting}>Cancel</Button><Button type="submit" disabled={isImporting}>{isImporting?'Saving…':'Save Camera'}</Button></footer></form></div>
}
const overlay={position:'fixed',inset:0,zIndex:3000,display:'grid',placeItems:'center',padding:14,background:'rgba(0,0,0,.82)'},choiceModal={width:'min(680px,94vw)',background:'var(--surface)',border:'1px solid var(--border)',borderRadius:13,overflow:'hidden',boxShadow:'var(--shadow)'},modal={...choiceModal,width:'min(1040px,96vw)',height:'min(820px,92vh)',display:'flex',flexDirection:'column'},header={display:'flex',alignItems:'center',justifyContent:'space-between',padding:'15px 18px',borderBottom:'1px solid var(--border)'},sub={marginTop:3,color:'var(--text2)',fontSize:11},close={border:0,background:'transparent',color:'var(--text2)',fontSize:22,cursor:'pointer'},choiceGrid={display:'grid',gridTemplateColumns:'repeat(2,minmax(0,1fr))',gap:12,padding:20},choice={minHeight:190,display:'grid',placeItems:'center',alignContent:'center',gap:8,padding:22,borderRadius:12,border:'1px solid var(--border)',background:'var(--surface2)',color:'var(--text)',cursor:'pointer',textAlign:'center'},choiceIcon={width:46,height:46,display:'grid',placeItems:'center',borderRadius:11,background:'var(--accent-soft)',border:'1px solid var(--accent-border)',color:'var(--accent-strong)',fontSize:22,fontWeight:800},uploadBox={display:'grid',gap:11,padding:20,border:'1px dashed var(--accent-border)',borderRadius:11,background:'var(--accent-soft)',color:'var(--text2)'},formPane={padding:17,overflowY:'auto'},mapPane={position:'relative',minHeight:430,background:'#000'},mapLabel={position:'absolute',top:10,left:10,zIndex:500,padding:'6px 9px',borderRadius:7,background:'rgba(0,0,0,.78)',border:'1px solid var(--border-strong)',fontSize:10,color:'var(--text)'},body={display:'grid',gridTemplateColumns:'minmax(310px,.92fr) minmax(420px,1.08fr)',minHeight:0,flex:1},labelStyle={display:'grid',gap:5,marginBottom:11,fontSize:12,color:'var(--text2)'},input={width:'100%',padding:'9px 10px',borderRadius:8,border:'1px solid var(--border)',background:'var(--surface2)',color:'var(--text)',fontSize:13},footer={display:'flex',justifyContent:'flex-end',gap:8,padding:12,borderTop:'1px solid var(--border)',background:'var(--surface)'},errorBox={marginTop:10,padding:9,borderRadius:8,border:'1px solid rgba(248,113,113,.4)',background:'rgba(248,113,113,.08)',color:'var(--red)',fontSize:11},resultBox={padding:9,borderRadius:8,border:'1px solid rgba(74,222,128,.3)',background:'rgba(74,222,128,.06)',color:'var(--green)',fontSize:11}
