import { useMemo, useState } from 'react'
import { Input } from './ui/input'

const SearchIcon=()=> <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round"><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></svg>
const PinIcon=()=> <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round"><path d="M20 10c0 5-8 12-8 12S4 15 4 10a8 8 0 1 1 16 0Z"/><circle cx="12" cy="10" r="2.5"/></svg>

export default function MapSearch({cameras=[],onLocate}){
 const[q,setQ]=useState('');const results=useMemo(()=>{const n=q.trim().toLowerCase();if(!n)return[];return cameras.filter(c=>[c.name,c.location,c.department,c.external_id,c.stream_id].some(v=>String(v??'').toLowerCase().includes(n))).slice(0,12)},[q,cameras])
 return <div className="sentinel-map-search" style={{position:'absolute',top:14,left:'50%',transform:'translateX(-50%)',zIndex:1200,width:'min(360px,calc(100% - 28px))'}}><div style={{position:'relative'}}><span className="sentinel-map-search-icon" style={{position:'absolute',left:11,top:'50%',transform:'translateY(-50%)',color:'#9c8f82',pointerEvents:'none'}}><SearchIcon/></span><Input value={q} onChange={e=>setQ(e.target.value)} placeholder="Find camera or area…" aria-label="Find camera or area" style={{paddingLeft:34,height:40,background:'rgba(0,0,0,.9)',borderColor:'rgba(249,115,22,.24)',boxShadow:'0 10px 28px rgba(0,0,0,.42)'}}/></div>{q.trim()&&<div className="sentinel-map-search-results" style={{marginTop:6,maxHeight:300,overflowY:'auto',background:'rgba(0,0,0,.96)',border:'1px solid rgba(249,115,22,.22)',borderRadius:10,boxShadow:'0 18px 45px rgba(0,0,0,.62)'}}>{results.length?results.map(c=><button className="sentinel-map-search-result" key={c.id} onClick={()=>{setQ(c.name||'');onLocate?.(c)}} style={{width:'100%',display:'flex',alignItems:'center',gap:9,textAlign:'left',padding:'9px 10px',border:0,borderBottom:'1px solid rgba(255,255,255,.08)',background:'transparent',color:'#fff',cursor:'pointer'}}><span style={{color:'var(--accent)'}}><PinIcon/></span><span style={{minWidth:0,flex:1}}><strong style={{display:'block',fontSize:11}}>{c.name||`CAM-${c.stream_id}`}</strong><small className="sentinel-map-search-muted" style={{display:'block',marginTop:2,color:'#9ca3af',overflow:'hidden',textOverflow:'ellipsis',whiteSpace:'nowrap'}}>{c.location||'Location not registered'} · {c.department||'Unassigned'}</small></span></button>):<div className="sentinel-map-search-empty" style={{padding:14,color:'#9ca3af',fontSize:11}}>No matching camera or area</div>}</div>}</div>
}
