import React from 'react'
import { SidebarProvider, Sidebar, SidebarHeader, SidebarContent, SidebarFooter, SidebarGroup, SidebarGroupLabel, SidebarGroupContent, SidebarMenu, SidebarMenuItem, SidebarMenuButton, SidebarTrigger } from './ui/sidebar'
import { DropdownMenu, DropdownMenuTrigger, DropdownMenuContent, DropdownMenuItem, DropdownMenuLabel, DropdownMenuSeparator } from './ui/dropdown-menu'
const Icon=({children})=><svg width="17" height="17" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">{children}</svg>
const Shield=()=> <Icon><path d="M12 3 5 6v5c0 4.7 2.8 8.2 7 10 4.2-1.8 7-5.3 7-10V6l-7-3Z"/><path d="m9.5 12 1.7 1.8 3.7-4"/></Icon>
const Camera=()=> <Icon><path d="M15 10l4.5-2.1A1 1 0 0121 8.8v6.4a1 1 0 01-1.5.9L15 14"/><rect x="2" y="6" width="13" height="12" rx="2"/></Icon>
const Map=()=> <Icon><path d="m9 18-6 3V6l6-3 6 3 6-3v15l-6 3-6-3Z"/><path d="M9 3v15M15 6v15"/></Icon>
const Search=()=> <Icon><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></Icon>
const Bell=()=> <Icon><path d="M18 8A6 6 0 0 0 6 8c0 5-2.2 7.3-3 8.5h18C20.2 15.3 18 13 18 8Z"/><path d="M13.7 21a2 2 0 0 1-3.4 0"/></Icon>
const List=()=> <Icon><path d="M8 6h13M8 12h13M8 18h13M3 6h.01M3 12h.01M3 18h.01"/></Icon>
const Tools=()=> <Icon><path d="M14.7 6.3a4 4 0 0 0-5.4 5.4L4 17l3 3 5.3-5.3a4 4 0 0 0 5.4-5.4l-2.2 2.2-2.8-.6-.6-2.8 2.2-2.2Z"/></Icon>
const Beaker=()=> <Icon><path d="M8 3h8M10 3v5l-4.5 8A3.5 3.5 0 0 0 8.6 21h6.8a3.5 3.5 0 0 0 3.1-5L14 8V3"/><path d="M7 15h10"/></Icon>
const Chevron=()=> <Icon><path d="m6 9 6 6 6-6"/></Icon>
const routes=[['/feeds','Monitor',Camera],['/map','GIS Map',Map],['/investigations','Investigate',Search],['/alerts','Alerts',Bell]]
export default function Navbar({alertCount=0,onWatchlistOpen,onOnboardOpen,onVendorsOpen,onTestOpen,testMode,principal,onLogout,path='/',onNavigate}){
 const open=localStorage.getItem('sentinel.sidebar.open.v1')!=='false',admin=principal&&['ADMIN','SUPERADMIN'].includes(principal.role),go=t=>e=>{e.preventDefault();onNavigate?.(t);if(t==='/alerts')window.dispatchEvent(new CustomEvent('sentinel:open-alerts'))}
 return <SidebarProvider defaultOpen={open} onOpenChange={v=>localStorage.setItem('sentinel.sidebar.open.v1',String(v))}><Sidebar><SidebarHeader><div className="ui-sidebar-header-main"><a href="/feeds" onClick={go('/feeds')} className="ui-sidebar-brand" aria-label="Sentinel AI home"><span className="ui-sidebar-brand-mark"><Shield/></span><span className="ui-sidebar-header-text"><span className="ui-sidebar-brand-title">SENTINEL AI</span><span className="ui-sidebar-brand-sub">Gujarat Police Operations</span></span></a><SidebarTrigger/></div></SidebarHeader><SidebarContent><SidebarGroup><SidebarGroupLabel>Operations</SidebarGroupLabel><SidebarGroupContent><SidebarMenu>{routes.map(([href,label,Item])=><SidebarMenuItem key={href}><SidebarMenuButton href={href} onClick={go(href)} active={path===href} tooltip={label}><Item/><span>{label}{href==='/alerts'&&alertCount>0?` · ${Math.min(alertCount,99)}`:''}</span></SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu></SidebarGroupContent></SidebarGroup><SidebarGroup><SidebarGroupLabel>Tools</SidebarGroupLabel><SidebarGroupContent><SidebarMenu><SidebarMenuItem><SidebarMenuButton href="#" onClick={e=>{e.preventDefault();onWatchlistOpen?.()}} tooltip="Watchlist"><List/><span>Watchlist</span></SidebarMenuButton></SidebarMenuItem>{admin&&<><SidebarMenuItem><SidebarMenuButton href="#" onClick={e=>{e.preventDefault();onOnboardOpen?.()}} tooltip="Camera Registry"><Camera/><span>Camera Registry</span></SidebarMenuButton></SidebarMenuItem><SidebarMenuItem><SidebarMenuButton href="#" onClick={e=>{e.preventDefault();onVendorsOpen?.()}} tooltip="Vendors & Models"><Tools/><span>Vendors & Models</span></SidebarMenuButton></SidebarMenuItem></>}{admin&&onTestOpen&&<SidebarMenuItem><SidebarMenuButton href="/test" onClick={e=>{e.preventDefault();onNavigate?.('/test');onTestOpen()}} active={path==='/test'||testMode} tooltip="Test Mode"><Beaker/><span>{testMode?'Exit Test Mode':'Test Mode'}</span></SidebarMenuButton></SidebarMenuItem>}</SidebarMenu></SidebarGroupContent></SidebarGroup></SidebarContent><SidebarFooter>{principal?.id&&<DropdownMenu><DropdownMenuTrigger asChild><button type="button" className="sentinel-user-trigger" title="User profile"><span className="sentinel-avatar">{String(principal.username||'?').slice(0,1).toUpperCase()}</span><span className="sentinel-user-meta"><span className="sentinel-user-name">{principal.username}</span><span className="sentinel-user-role">{principal.role}</span></span><Chevron/></button></DropdownMenuTrigger><DropdownMenuContent align="start"><DropdownMenuLabel>Signed in</DropdownMenuLabel><DropdownMenuItem disabled>{principal.username} · {principal.role}</DropdownMenuItem><DropdownMenuSeparator/><DropdownMenuItem onSelect={onLogout}>Sign out</DropdownMenuItem></DropdownMenuContent></DropdownMenu>}</SidebarFooter></Sidebar></SidebarProvider>
}
