import { useEffect, useRef, useState } from 'react'
import L from 'leaflet'
import 'leaflet/dist/leaflet.css'
import { api } from '../api/client'

const GUJARAT_BOUNDS=L.latLngBounds([20.08,68.08],[24.55,74.55]),VIEW_KEY='sentinel.onboard.map.viewport.session.v1'
const fields=[['name','Camera name',true],['stream_id','Stream ID'],['location','Location'],['department','Department'],['owner_organization','Owner'],['rtsp_url','RTSP URL'],['hls_url','HLS URL'],['lat','Latitude'],['lng','Longitude']]
const pinIcon=L.divIcon({className:'sentinel-onboard-pin',iconSize:[30,38],iconAnchor:[15,38],html:'<div style="width:30px;height:30px;border-radius:50% 50% 50% 0;background:#f59e0b;border:3px solid #fff;transform:rotate(-45deg);box-shadow:0 2px 8px rgba(0,0,0,.45)"><span style="display:block;width:9px;height:9px;border-radius:50%;background:#111;margin:7px auto"></span></div>'})
export default function OnboardCameraModal({onClose,onSaved,onImport}){
 const mapNode=useRef(null),mapRef=useRef(null),markerRef=useRef(null)
 const[form,setForm]=useState({name:'',stream_id:'',location:'',lat:'',lng:'',rtsp_url:'',hls_url:'',department:'',owner_organization:'',vendor_id:'',model_id:''}),[error,setError]=useState(''),[busy,setBusy]=useState(false),[file,setFile]=useState(null),[importResult,setImportResult]=useState(null),[vendors,setVendors]=useState([]),[models,setModels]=useState([])
 const setCoords=(lat,lng)=>setForm(v=>({...v,lat:Number(lat).toFixed(6),lng:Number(lng).toFixed(6)}))
 useEffect(()=>{let saved=null;try{saved=JSON.parse(sessionStorage.getItem(VIEW_KEY)||'null')}catch{};const map=L.map(mapNode.current,{zoomControl:true,maxBounds:GUJARAT_BOUNDS.pad(.55),maxBoundsViscosity:.72});L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'OpenStreetMap contributors',maxZoom:19}).addTo(map);map.fitBounds(saved?.center&&Number.isFinite(saved.zoom)?L.latLngBounds([[saved.center[0],saved.center[1]],[saved.center[0],saved.center[1]]]).pad(0):GUJARAT_BOUNDS,{animate:false});if(saved?.center&&Number.isFinite(saved.zoom))map.setView(saved.center,saved.zoom,{animate:false});map.on('click',e=>setCoords(e.latlng.lat,e.latlng.lng));map.on('moveend',()=>{const c=map.getCenter();sessionStorage.setItem(VIEW_KEY,JSON.stringify({center:[c.lat,c.lng],zoom:map.getZoom()}))});mapRef.current=map;requestAnimationFrame(()=>map.invalidateSize());return()=>map.remove()},[])
 useEffect(()=>{api.getVendors().then(setVendors).catch(()=>setVendors([]))},[])
 useEffect(()=>{if(!form.vendor_id){setModels([]);return}api.getVendorModels(form.vendor_id).then(setModels).catch(()=>setModels([]))},[form.vendor_id])
 useEffect(()=>{const lat=Number(form.lat),lng=Number(form.lng),map=mapRef.current;if(!map||!Number.isFinite(lat)||!Number.isFinite(lng))return;if(!markerRef.current){markerRef.current=L.marker([lat,lng],{draggable:true,icon:pinIcon,title:'Camera location'}).addTo(map);markerRef.current.on('dragend',e=>{const p=e.target.getLatLng();setCoords(p.lat,p.lng)})}else markerRef.current.setLatLng([lat,lng]);map.panTo([lat,lng])},[form.lat,form.lng])
 const change=e=>setForm(v=>({...v,[e.target.name]:e.target.value}))
 const submit=async e=>{e.preventDefault();setBusy(true);setError('');try{await onSaved({...form,stream_id:form.stream_id?Number(form.stream_id):undefined,vendor_id:form.vendor_id||undefined,model_id:form.model_id||undefined,lat:form.lat===''?undefined:Number(form.lat),lng:form.lng===''?undefined:Number(form.lng),coord_source:form.lat&&form.lng?'manual':'unknown',coord_confidence:form.lat&&form.lng?1:undefined});onClose()}catch(err){setError(err.message||'Unable to onboard camera')}finally{setBusy(false)}}
 const importCsv=async()=>{if(!file)return;setBusy(true);setError('');try{setImportResult(await onImport(file))}catch(err){setError(err.message||'Unable to import registry')}finally{setBusy(false)}}
 return <div onClick={e=>e.target===e.currentTarget&&onClose()} style={overlay}><form onSubmit={submit} style={modal}><header style={header}><b>Onboard camera</b><button type="button" onClick={onClose} style={close}>×</button></header><section style={{display:'grid',gridTemplateColumns:'minmax(300px,.9fr) minmax(360px,1.1fr)',minHeight:0,flex:1}}><div style={{padding:15,overflowY:'auto'}}><div style={{marginBottom:14,paddingBottom:12,borderBottom:'1px solid var(--border)'}}><b style={{fontSize:13}}>Bulk registry import</b><label style={labelStyle}>Registry CSV or XLSX<input type="file" accept=".csv,.xlsx,text/csv,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" onChange={e=>setFile(e.target.files?.[0]||null)} style={input}/></label><button type="button" disabled={busy||!file} onClick={importCsv} style={secondary}>Import and audit</button>{importResult&&<small style={{display:'block',marginTop:6,color:importResult.rejected_rows?'var(--medium)':'var(--green)'}}>Imported {importResult.accepted_rows}/{importResult.total_rows}; rejected {importResult.rejected_rows}.</small>}</div>{fields.map(([name,label,required])=><label key={name} style={labelStyle}>{label}<input name={name} value={form[name]} required={required} onChange={change} style={input}/></label>)}<label style={labelStyle}>Vendor<select name="vendor_id" value={form.vendor_id} onChange={e=>{change(e);setForm(v=>({...v,model_id:''}))}} style={input}><option value="">Unspecified</option>{vendors.map(v=><option key={v.id} value={v.id}>{v.name}</option>)}</select></label><label style={labelStyle}>Camera model<select name="model_id" value={form.model_id} disabled={!form.vendor_id} onChange={change} style={input}><option value="">Unspecified</option>{models.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label><small style={{color:'var(--text2)'}}>Gujarat is the default view. Pan and zoom are preserved only for this browser session; click or drag the pin to set coordinates.</small>{error&&<p style={{color:'var(--red)',fontSize:12}}>{error}</p>}</div><div ref={mapNode} style={{minHeight:420,background:'#171613'}}/></section><footer style={{padding:12,display:'flex',justifyContent:'flex-end',gap:8,borderTop:'1px solid var(--border)',background:'var(--surface)'}}><button type="button" onClick={onClose} style={secondary}>Cancel</button><button type="submit" disabled={busy} style={primary}>{busy?'Saving…':'Save camera'}</button></footer></form></div>
}
const overlay={position:'fixed',inset:0,zIndex:3000,display:'grid',placeItems:'center',background:'rgba(0,0,0,.72)',padding:12},modal={width:'min(980px,96vw)',height:'min(780px,92vh)',display:'flex',flexDirection:'column',overflow:'hidden',background:'var(--surface)',border:'1px solid var(--border)',borderRadius:10,boxShadow:'var(--shadow)'},header={display:'flex',justifyContent:'space-between',alignItems:'center',padding:'14px 16px',borderBottom:'1px solid var(--border)'},close={border:0,background:'transparent',color:'var(--text)',cursor:'pointer',fontSize:22},labelStyle={display:'grid',gap:5,marginBottom:10,fontSize:12,color:'var(--text2)'},input={padding:'8px 9px',borderRadius:7,border:'1px solid var(--border)',background:'var(--surface2)',color:'var(--text)',fontSize:13},secondary={padding:'8px 11px',borderRadius:7,border:'1px solid var(--border)',background:'var(--surface2)',color:'var(--text)',cursor:'pointer',fontWeight:650},primary={...secondary,borderColor:'var(--accent)',background:'var(--accent)',color:'#100d08'}
