import { useEffect, useRef, useState } from 'react'
import { api } from '../api/client'
import { Input } from './ui/input'
import { Button } from './ui/button'

const overlay={position:'fixed',inset:0,background:'rgba(0,0,0,.78)',display:'flex',alignItems:'center',justifyContent:'center',zIndex:1000,padding:16}
const modal={background:'linear-gradient(180deg,#141311,#0d0d0c)',borderRadius:12,border:'1px solid var(--border-strong)',width:'min(760px,96vw)',maxHeight:'88vh',display:'flex',flexDirection:'column',overflow:'hidden',boxShadow:'0 26px 90px rgba(0,0,0,.6)'}
const metadata=camera=>{const width=camera.effective_width??camera.width,height=camera.effective_height??camera.height,fps=camera.effective_fps??camera.fps,values=[];if(camera.effective_codec||camera.codec)values.push(camera.effective_codec||camera.codec);if(Number(width)>0&&Number(height)>0)values.push(`${width} x ${height}`);if(Number(fps)>0)values.push(`${Number(fps).toFixed(1)} FPS`);return values.join(' · ')||'Stream metadata unavailable'}
const SearchIcon=()=> <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round"><circle cx="11" cy="11" r="8"/><line x1="21" y1="21" x2="16.65" y2="16.65"/></svg>
const LiveIcon=()=> <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M15 10l4.553-2.069A1 1 0 0121 8.82v6.36a1 1 0 01-1.447.893L15 14"/><rect x="1" y="6" width="15" height="12" rx="2"/></svg>
const MapPinIcon=()=> <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M20 10c0 5-8 12-8 12S4 15 4 10a8 8 0 1116 0Z"/><circle cx="12" cy="10" r="2.5"/></svg>
const CloseIcon=()=> <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round"><path d="m18 6-12 12M6 6l12 12"/></svg>
const actionButton={width:34,height:32,display:'grid',placeItems:'center',borderRadius:6,border:'1px solid var(--accent-border)',background:'var(--accent-soft)',color:'var(--accent)',cursor:'pointer',padding:0}

export default function SearchModal({onClose,onViewCamera,onLocateCamera,onLocateRoute,init,testMode=false,testSession=null}) {
 const [tab,setTab]=useState('camera'),[query,setQuery]=useState(''),[submitted,setSubmitted]=useState(''),[results,setResults]=useState(null),[loading,setLoading]=useState(false),[error,setError]=useState(''),[journeyLoading,setJourneyLoading]=useState(null)
 const controllerRef=useRef(null),sequenceRef=useRef(0)
 useEffect(()=>{if(init?.tab)setTab(init.tab);if(init?.query){setQuery(init.query);setSubmitted(init.query)}},[init])
 useEffect(()=>{const value=query.trim();controllerRef.current?.abort();if(tab!=='camera')return;if(value.length<1){setResults(null);setLoading(false);setError('');return}const controller=new AbortController(),request=++sequenceRef.current;controllerRef.current=controller;const timer=setTimeout(async()=>{setLoading(true);setError('');try{let response;if(testMode&&testSession){const cameras=await api.getTestCameras(testSession.id),needle=value.toLowerCase();response={query:value,items:cameras.filter(camera=>[camera.id,camera.stream_id,camera.name,camera.location,camera.status].some(field=>String(field??'').toLowerCase().includes(needle))),limit:20,offset:0}}else response=await api.searchCameras(value,{signal:controller.signal});if(request===sequenceRef.current)setResults(response)}catch(err){if(err.name!=='AbortError'&&request===sequenceRef.current)setError(err.message)}finally{if(request===sequenceRef.current)setLoading(false)}},220);return()=>{clearTimeout(timer);controller.abort()}},[query,tab,testMode,testSession?.id])
 const executePlateSearch=async()=>{const value=query.trim();if(value.length<3){setError('Enter at least 3 characters before investigating.');return}controllerRef.current?.abort();setSubmitted(value);setLoading(true);setError('');try{const response=testMode&&testSession?await api.getTestResults(testSession.id,{plate:value,detection_type:'plate',limit:100}):await api.searchPlate(value);setResults(response)}catch(err){setError(err.message);setResults(null)}finally{setLoading(false)}}
 const executeSearch=async()=>{if(tab==='plate')return executePlateSearch();if(!query.trim())return;setSubmitted(query.trim())}
 const handleKeyDown=event=>{if(event.key==='Enter'&&!event.shiftKey){event.preventDefault();executeSearch()}}
 const switchTab=next=>{controllerRef.current?.abort();setTab(next);setQuery('');setSubmitted('');setResults(null);setError('')}
 const showJourney=async sighting=>{const track=sighting.global_vehicle_id||sighting.track_id;if(!track)return;setJourneyLoading(sighting.id);try{const journey=await api.searchTrack(track);onLocateRoute?.(journey.sightings||[])}catch(err){setError(err.message)}finally{setJourneyLoading(null)}}
 return <div style={overlay} onClick={event=>event.target===event.currentTarget&&onClose()}><section style={modal} role="dialog" aria-modal="true" aria-label={tab==='plate'?'Vehicle investigation':'Camera search'}>
  <header style={{padding:'14px 18px',borderBottom:'1px solid var(--border)',display:'flex',justifyContent:'space-between',alignItems:'center'}}><div><b style={{fontSize:15}}>Search & Investigation</b><div style={{fontSize:10,color:'var(--text2)',marginTop:3}}>{tab==='plate'?'Submit to investigate confirmed plate sightings.':'Find a camera and route directly to live feed or map.'}</div></div><button onClick={onClose} aria-label="Close search" title="Close" className="ui-icon-button"><CloseIcon/></button></header>
  <nav style={{display:'flex',gap:2,padding:'8px 12px 0',borderBottom:'1px solid var(--border)',background:'rgba(0,0,0,.08)'}}>{[['camera','Camera registry'],['plate','License plate investigation']].map(([key,label])=><button key={key} onClick={()=>switchTab(key)} style={{padding:'9px 14px',border:'1px solid transparent',borderBottom:`2px solid ${tab===key?'var(--accent)':'transparent'}`,background:'transparent',color:tab===key?'var(--accent)':'var(--text2)',cursor:'pointer',fontSize:12,fontWeight:tab===key?700:500}}>{label}</button>)}</nav>
  <div style={{padding:'14px 18px',borderBottom:'1px solid var(--border)'}}><div style={{display:'flex',gap:8}}><div style={{position:'relative',flex:1}}><div style={{position:'absolute',left:11,top:10,color:'var(--text2)',pointerEvents:'none'}}><SearchIcon/></div><Input autoFocus value={query} onChange={event=>setQuery(event.target.value)} onKeyDown={handleKeyDown} className="sentinel-modal-search-input" placeholder={tab==='camera'?'Camera ID, name, department, location, status…':'Enter number plate, e.g. GJ03AA1234'} aria-label={tab==='camera'?'Camera search':'License plate investigation'}/></div><Button type="button" variant="primary" size="sm" onClick={executeSearch} disabled={loading||(tab==='camera'?query.trim().length<1:query.trim().length<3)}>{loading?'Working…':tab==='plate'?'Investigate':'Search'}</Button></div><div style={{display:'flex',alignItems:'center',gap:8,color:'var(--text2)',fontSize:10,marginTop:7}}>{tab==='camera'?<><span>Live registry search</span><span>•</span><span>{loading?'Refreshing results…':'Results update while typing; Search confirms the current query.'}</span></>:<><span style={{color:'var(--accent)'}}>ANPR investigation</span><span>•</span><span>{submitted?'Submitted: '+submitted:'Submit to run the plate investigation.'}</span></>}</div></div>
  <main style={{flex:1,overflowY:'auto',padding:'14px 18px 18px'}}>{error&&<div style={{padding:'9px 10px',marginBottom:10,borderRadius:7,border:'1px solid rgba(239,68,68,.4)',background:'rgba(239,68,68,.08)',color:'var(--high)',fontSize:11}}>{error}</div>}
   {results&&tab==='camera'&&(results.items?.length?results.items.map(camera=><article key={camera.id} style={{padding:'11px 12px',marginBottom:7,borderRadius:8,background:'rgba(255,255,255,.018)',border:'1px solid var(--border)',fontSize:12}}><div style={{display:'flex',gap:12,alignItems:'center'}}><div style={{minWidth:0,flex:1}}><div style={{display:'flex',alignItems:'center',gap:8,flexWrap:'wrap'}}><b>CAM-{String(camera.stream_id||'?').padStart(2,'0')}</b><span style={{fontWeight:650}}>{camera.name}</span><span style={{fontSize:9,padding:'2px 5px',borderRadius:4,background:camera.health_status==='healthy'?'rgba(34,197,94,.1)':'rgba(234,179,8,.1)',color:camera.health_status==='healthy'?'var(--green)':'var(--medium)'}}>{(camera.health_status||camera.status||'unknown').toUpperCase()}</span></div><div style={{color:'var(--text2)',marginTop:4}}>{camera.location||'Location not registered'} · {camera.department||'Department not registered'}</div><div style={{color:'var(--text2)',fontSize:10,marginTop:4}}>{metadata(camera)}</div></div><div style={{display:'flex',gap:5}}><button onClick={()=>onViewCamera?.(camera)} title="View Live Feed" aria-label="View Live Feed" style={actionButton}><LiveIcon/></button><button onClick={()=>onLocateCamera?.(camera)} title="Locate on Map" aria-label="Locate on Map" style={actionButton}><MapPinIcon/></button></div></div></article>):<div style={{padding:25,textAlign:'center',color:'var(--text2)',fontSize:12}}>No cameras found</div>)}
   {results&&tab==='plate'&&<>{results.watchlist_hits?.length>0&&<div style={{marginBottom:12,padding:10,borderRadius:7,background:'rgba(239,68,68,.08)',border:'1px solid var(--high)',fontSize:12}}><b style={{color:'var(--high)'}}>Watchlist match</b>{results.watchlist_hits.map(hit=><div key={hit.id} style={{marginTop:3}}>{hit.name} — {hit.description}</div>)}</div>}{results.detections?.length?results.detections.map(detection=><article key={detection.id} style={{padding:'10px 12px',marginBottom:7,borderRadius:8,background:'rgba(255,255,255,.018)',border:'1px solid var(--border)',fontSize:12}}><div style={{display:'flex',alignItems:'center',justifyContent:'space-between',gap:8}}><div><b style={{fontFamily:'monospace',letterSpacing:1}}>{detection.plate_text}</b><span style={{color:'var(--text2)',marginLeft:8}}>{detection.cam_name}</span></div><span style={{color:'var(--text2)',fontSize:10}}>{new Date(detection.timestamp).toLocaleString()}</span></div><div style={{marginTop:7}}><button onClick={()=>showJourney(detection)} disabled={(!detection.global_vehicle_id&&!detection.track_id)||journeyLoading===detection.id} style={{padding:'5px 8px',borderRadius:5,border:'1px solid var(--accent-border)',background:'var(--accent-soft)',color:'var(--accent)',cursor:'pointer',fontSize:10}}>{journeyLoading===detection.id?'Loading route…':'Show vehicle journey'}</button></div></article>):<div style={{padding:25,textAlign:'center',color:'var(--text2)',fontSize:12}}>No sightings found for this investigation.</div>}</>}
  </main>
 </section></div>
}
