const BASE=import.meta.env.VITE_API_URL||'/api'
const TEST_SESSION_KEY='sentinel.test.session.v1'
const AUTH_TOKEN_KEY='sentinel.jwt'
const readAuthToken=()=>{try{return localStorage.getItem(AUTH_TOKEN_KEY)||sessionStorage.getItem(AUTH_TOKEN_KEY)||localStorage.getItem('sentinel_token')||sessionStorage.getItem('sentinel_token')}catch{return null}}
async function req(path,opts={}){const token=readAuthToken(),isForm=opts.body instanceof FormData;const res=await fetch(`${BASE}${path}`,{headers:{...(isForm?{}:{'Content-Type':'application/json'}),...(token?{Authorization:`Bearer ${token}`}:{}) ,...opts.headers},...opts});if(!res.ok){const detail=await res.json().catch(()=>null);const err=new Error(detail?.detail?.message||`${res.status} ${res.statusText}`);err.status=res.status;err.detail=detail?.detail;throw err}return res.json()}
const upload=(path,file,query='')=>{const d=new FormData();d.append('file',file);return req(`${path}${query}`,{method:'POST',body:d,headers:{}})}
const activeTestSessionId=()=>{try{return sessionStorage.getItem(TEST_SESSION_KEY)}catch{return null}}
export const api={
 getCameras:()=>req('/cameras/'),getAuthConfig:()=>req('/auth/config'),getMe:()=>req('/auth/me'),login:body=>req('/auth/login',{method:'POST',body:JSON.stringify(body)}),logout:()=>req('/auth/logout',{method:'POST'}),refresh:()=>req('/auth/refresh',{method:'POST'}),
 getCameraStats:()=>req('/cameras/stats/summary'),getPipelineStats:()=>req('/cameras/pipeline/stats'),getRecentAnalytics:()=>req('/cameras/analytics/recent'),getAlerts:(p={},opts={})=>req('/alerts/?'+new URLSearchParams(p),opts),getAlertCounts:()=>req('/alerts/stats/counts'),ackAlert:id=>req(`/alerts/${id}/acknowledge`,{method:'POST'}),getSnapshotToken:id=>req(`/cameras/${id}/snapshot-token`),
 transitionAlert:(id,status,reason='')=>req(`/alerts/${id}/transition?target_status=${encodeURIComponent(status)}${reason?`&reason=${encodeURIComponent(reason)}`:''}`,{method:'POST'}),transitionTestAlert:(sessionId,id,status,reason='')=>req(`/test/sessions/${sessionId}/alerts/${id}/transition?target_status=${encodeURIComponent(status)}${reason?`&reason=${encodeURIComponent(reason)}`:''}`,{method:'POST'}),
 getWatchlist:()=>req('/watchlist/'),addWatchlist:body=>req('/watchlist/',{method:'POST',body:JSON.stringify(body)}),addWatchlistPersonPhoto:(body,file)=>{const d=new FormData();d.append('name',body.name);d.append('description',body.description||'');d.append('alert_priority',body.alert_priority||'HIGH');d.append('file',file);return req('/watchlist/person-photo',{method:'POST',body:d,headers:{}})},removeWatchlist:id=>req(`/watchlist/${id}`,{method:'DELETE'}),
 searchCameras:(q,opts={})=>req(`/search/cameras?q=${encodeURIComponent(q)}`,opts),searchPlate:(q,opts={})=>{const headers={...(opts.headers||{})};if(opts.testSessionId)headers['X-Test-Session-Id']=opts.testSessionId;return req(`/search/plate?q=${encodeURIComponent(q)}`,{...opts,headers})},searchTrack:id=>req(`/search/track/${id}`),recentAlerts:(m,p)=>req(`/search/alerts/recent?minutes=${m}${p?`&priority=${p}`:''}`),validatePersonPhoto:file=>{const d=new FormData();d.append('file',file);const session=activeTestSessionId();return req('/search/person/validate',{method:'POST',body:d,headers:session?{'X-Test-Session-Id':session}:{}})},investigatePerson:(files,opts={})=>{const d=new FormData();for(const file of files)d.append('files',file);const session=opts.testSessionId||activeTestSessionId();return req('/search/person/investigate',{method:'POST',body:d,headers:session?{'X-Test-Session-Id':session}:{}})},verifyAudit:()=>req('/operations/audit/verify'),
 onboardCamera:body=>req('/cameras/onboard',{method:'POST',body:JSON.stringify(body)}),importCameras:(file,acknowledgeWarnings=false)=>upload('/camera-imports/import',file,`?acknowledge_warnings=${acknowledgeWarnings?'true':'false'}`),validateCameraImport:file=>upload('/camera-imports/validate',file),
 getCameraHealthHistory:(id,minutes=60)=>req(`/operations/cameras/${id}/health?minutes=${minutes}`),getCameraHealthSummary:()=>req('/operations/cameras/health/summary'),getOperationsOverview:()=>req('/operations/overview'),
 getVendors:()=>req('/vendors/'),createVendor:body=>req('/vendors/',{method:'POST',body:JSON.stringify(body)}),updateVendor:(id,body)=>req(`/vendors/${id}`,{method:'PUT',body:JSON.stringify(body)}),deleteVendor:id=>req(`/vendors/${id}`,{method:'DELETE'}),getVendorModels:id=>req(`/vendors/${id}/models`),createVendorModel:(id,body)=>req(`/vendors/${id}/models`,{method:'POST',body:JSON.stringify(body)}),updateVendorModel:(vid,mid,body)=>req(`/vendors/${vid}/models/${mid}`,{method:'PUT',body:JSON.stringify(body)}),deleteVendorModel:(vid,mid)=>req(`/vendors/${vid}/models/${mid}`,{method:'DELETE'}),
 getTestAssets:()=>req('/test/assets'),uploadTestVideo:file=>upload('/test/feeds/upload',file),createTestSession:body=>req('/test/sessions',{method:'POST',body:JSON.stringify(body)}),getActiveTestSession:()=>req('/test/sessions/active'),getTestStatus:id=>req(`/test/sessions/${id}/status`),getTestCameras:id=>req(`/test/sessions/${id}/cameras`),getTestResults:(id,p={})=>req(`/test/sessions/${id}/results?${new URLSearchParams(p)}`),closeTestSession:id=>req(`/test/sessions/${id}`,{method:'DELETE'}),
 downloadTestResults:async id=>{const token=readAuthToken(),r=await fetch(`${BASE}/test/sessions/${id}/results/export`,{headers:token?{Authorization:`Bearer ${token}`}:{}});if(!r.ok)throw new Error(`${r.status} ${r.statusText}`);return r.blob()},listEvidence:(p={},opts={})=>req('/evidence/?'+new URLSearchParams(p),opts),createEvidence:body=>req('/evidence/',{method:'POST',body:JSON.stringify(body)}),getEvidence:id=>req(`/evidence/${id}`),getEvidenceSignedToken:id=>req(`/evidence/${id}/signed-token`),downloadDetections:async()=>{const token=readAuthToken(),r=await fetch(`${BASE}/reports/detections?format=csv`,{headers:token?{Authorization:`Bearer ${token}`}:{}});if(!r.ok)throw new Error(`${r.status} ${r.statusText}`);return r.blob()}
}
export const WS_URL=import.meta.env.VITE_WS_URL||`${window.location.protocol==='https:'?'wss:':'ws:'}//${window.location.host}/ws/alerts`
