const BASE=import.meta.env.VITE_API_URL||'/api'
const TEST_SESSION_KEY='sentinel.test.session.v1'
const AUTH_TOKEN_KEY='sentinel.jwt'
let refreshPromise=null
const readAuthToken=()=>{try{return localStorage.getItem(AUTH_TOKEN_KEY)||sessionStorage.getItem(AUTH_TOKEN_KEY)||localStorage.getItem('sentinel_token')||sessionStorage.getItem('sentinel_token')}catch{return null}}
const storeAuthToken=token=>{try{if(token){localStorage.setItem(AUTH_TOKEN_KEY,token);sessionStorage.setItem(AUTH_TOKEN_KEY,token)}else{localStorage.removeItem(AUTH_TOKEN_KEY);sessionStorage.removeItem(AUTH_TOKEN_KEY);localStorage.removeItem('sentinel_token');sessionStorage.removeItem('sentinel_token')}}catch{}}
function accessTokenExpiry(token){try{const part=String(token||'').split('.')[1];if(!part)return 0;const json=JSON.parse(atob(part.replace(/-/g,'+').replace(/_/g,'/')));return Number(json.exp)||0}catch{return 0}}
async function ensureFreshAccessToken(minSeconds=60){const token=readAuthToken();if(!token)return null;const exp=accessTokenExpiry(token);const now=Math.floor(Date.now()/1000);if(exp && exp-now > minSeconds)return token;try{return await refreshAccessToken()}catch{return token}}
async function refreshAccessToken(){if(refreshPromise)return refreshPromise;refreshPromise=fetch(`${BASE}/auth/refresh`,{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'}}).then(async response=>{if(!response.ok)throw new Error('Session refresh failed');const payload=await response.json();if(payload?.access_token)storeAuthToken(payload.access_token);return payload?.access_token||null}).finally(()=>{refreshPromise=null});return refreshPromise}
async function req(path,opts={},retry=true){let token=readAuthToken();if(token&&!path.startsWith('/auth/login')&&!path.startsWith('/auth/refresh')&&!path.startsWith('/auth/config')) token=await ensureFreshAccessToken(60);const isForm=opts.body instanceof FormData;const headers={...(isForm?{}:{'Content-Type':'application/json'}),...(token?{Authorization:`Bearer ${token}`}:{}) ,...opts.headers};const res=await fetch(`${BASE}${path}`,{credentials:'include',headers,...opts});if(res.status===401&&retry&&!path.startsWith('/auth/')&&refreshPromise===null){try{const nextToken=await refreshAccessToken();if(nextToken)return req(path,opts,false)}catch{}storeAuthToken(null)}if(!res.ok){const detail=await res.json().catch(()=>null);const err=new Error(detail?.detail?.message||detail?.detail||`${res.status} ${res.statusText}`);err.status=res.status;err.detail=detail?.detail;throw err}return res.status===204?null:res.json()}
const upload=(path,file,query='')=>{const d=new FormData();d.append('file',file);return req(`${path}${query}`,{method:'POST',body:d,headers:{}})}
const activeTestSessionId=()=>{try{const raw=sessionStorage.getItem(TEST_SESSION_KEY)||sessionStorage.getItem('sentinel_test_session');if(!raw)return null;try{return JSON.parse(raw).session_id||JSON.parse(raw).id||null}catch{return raw}}catch{return null}}
const canonicalizeCameras=cameras=>(Array.isArray(cameras)?cameras:[]).filter(camera=>camera&&!camera.is_test&&!String(camera.id||'').startsWith('test-')).map(camera=>{const current=String(camera.hls_url||'');if(current.startsWith('/api/cctv/'))return camera;const raw=camera.external_id||camera.stream_id;const match=String(raw??'').trim().match(/^cam?(\d+)$/i);if(!match)return camera;const providerId=`cam${String(Number(match[1])).padStart(2,'0')}`;return {...camera,hls_url:`/api/cctv/${providerId}/index.m3u8`}})
export const api={
 getCameras:()=>req('/cameras/').then(payload=>canonicalizeCameras(Array.isArray(payload)?payload:(payload?.items||payload?.cameras||[]))),getAuthConfig:()=>req('/auth/config'),getMe:()=>req('/auth/me').then(user=>user?{...user,username:String(user.username||'').trim(),role:String(user.role||'VIEWER').trim().toUpperCase(),id:user.id??null}:user),login:body=>req('/auth/login',{method:'POST',body:JSON.stringify(body)}).then(payload=>payload?.user?{...payload,user:{...payload.user,username:String(payload.user.username||'').trim(),role:String(payload.user.role||'VIEWER').trim().toUpperCase(),id:payload.user.id??null}}:payload),logout:()=>req('/auth/logout',{method:'POST'}),refresh:()=>refreshAccessToken(),
 getCameraStats:()=>req('/cameras/stats/summary').then(payload=>Array.isArray(payload)?payload:(payload?.items||payload?.cameras||[])),getPipelineStats:()=>req('/cameras/pipeline/stats').then(payload=>payload||{}),getRecentAnalytics:()=>req('/cameras/analytics/recent').then(payload=>Array.isArray(payload)?payload:(payload?.items||payload?.analytics||[])),getAlerts:(p={},opts={})=>req('/alerts/?'+new URLSearchParams(p),opts).then(payload=>Array.isArray(payload)?payload:(payload?.items||payload?.alerts||[])),getAlertCounts:()=>req('/alerts/stats/counts').then(payload=>payload&&typeof payload==='object'?payload:{total:0,unacknowledged:0,high:0,medium:0,low:0}),ackAlert:id=>req(`/alerts/${id}/acknowledge`,{method:'POST'}),getSnapshotToken:id=>req(`/cameras/${id}/snapshot-token`),
 transitionAlert:(id,status,reason='')=>req(`/alerts/${id}/transition?target_status=${encodeURIComponent(status)}${reason?`&reason=${encodeURIComponent(reason)}`:''}`,{method:'POST'}),transitionTestAlert:(sessionId,id,status,reason='')=>req(`/test/sessions/${sessionId}/alerts/${id}/transition?target_status=${encodeURIComponent(status)}${reason?`&reason=${encodeURIComponent(reason)}`:''}`,{method:'POST'}),getTestAlerts:(sessionId,p={})=>req(`/test/sessions/${sessionId}/results?${new URLSearchParams(p)}`).then(r=>r.alerts||[]),
 getWatchlist:(opts={})=>req(opts.testSessionId?`/test/sessions/${opts.testSessionId}/watchlist/`:'/watchlist/'),addWatchlist:(body,opts={})=>req(opts.testSessionId?`/test/sessions/${opts.testSessionId}/watchlist/`:'/watchlist/',{method:'POST',body:JSON.stringify(body)}),addWatchlistPersonPhoto:(body,file,opts={})=>{const d=new FormData();d.append('name',body.name);d.append('description',body.description||'');d.append('alert_priority',body.alert_priority||'HIGH');d.append('file',file);const h=opts.testSessionId?{'X-Test-Session-Id':opts.testSessionId}:{};return req(opts.testSessionId?`/test/sessions/${opts.testSessionId}/watchlist/person-photo`:'/watchlist/person-photo',{method:'POST',body:d,headers:h})},removeWatchlist:(id,opts={})=>req(opts.testSessionId?`/test/sessions/${opts.testSessionId}/watchlist/${id}`:`/watchlist/${id}`,{method:'DELETE'}),
 searchCameras:(q,opts={})=>req(`/search/cameras?q=${encodeURIComponent(q)}`,opts),searchPlate:(q,opts={})=>{const headers={...(opts.headers||{})};if(opts.testSessionId)headers['X-Test-Session-Id']=opts.testSessionId;return req(`/search/plate?q=${encodeURIComponent(q)}`,{...opts,headers})},searchTrack:(id,opts={})=>{const h=opts.testSessionId?{'X-Test-Session-Id':opts.testSessionId}:{};return req(`/search/track/${id}`,{headers:h})},recentAlerts:(m,p)=>req(`/search/alerts/recent?minutes=${m}${p?`&priority=${p}`:''}`),validatePersonPhoto:file=>{const d=new FormData();d.append('file',file);const session=activeTestSessionId();return req('/search/person/validate',{method:'POST',body:d,headers:session?{'X-Test-Session-Id':session}:{}})},investigatePerson:(files,opts={})=>{const d=new FormData();for(const file of files)d.append('files',file);const session=opts.testSessionId||activeTestSessionId();return req('/search/person/investigate',{method:'POST',body:d,headers:session?{'X-Test-Session-Id':session}:{}})},verifyAudit:()=>req('/operations/audit/verify'),
 onboardCamera:body=>req('/cameras/onboard',{method:'POST',body:JSON.stringify(body)}),importCameras:(file,acknowledgeWarnings=false)=>upload('/camera-imports/import',file,`?acknowledge_warnings=${acknowledgeWarnings?'true':'false'}`),validateCameraImport:file=>upload('/camera-imports/validate',file),
 getCameraHealthHistory:(id,minutes=60)=>req(`/operations/cameras/${id}/health?minutes=${minutes}`),getCameraHealthSummary:()=>req('/operations/cameras/health/summary'),getOperationsOverview:()=>req('/operations/overview'),
 getVendors:()=>req('/vendors/'),createVendor:body=>req('/vendors/',{method:'POST',body:JSON.stringify(body)}),updateVendor:(id,body)=>req(`/vendors/${id}`,{method:'PUT',body:JSON.stringify(body)}),deleteVendor:id=>req(`/vendors/${id}`,{method:'DELETE'}),getVendorModels:id=>req(`/vendors/${id}/models`),createVendorModel:(id,body)=>req(`/vendors/${id}/models`,{method:'POST',body:JSON.stringify(body)}),updateVendorModel:(vid,mid,body)=>req(`/vendors/${vid}/models/${mid}`,{method:'PUT',body:JSON.stringify(body)}),deleteVendorModel:(vid,mid)=>req(`/vendors/${vid}/models/${mid}`,{method:'DELETE'}),
 getTestAssets:()=>req('/test/assets'),getTestState:id=>req(`/test/sessions/${id}/state`).then(payload=>payload&&typeof payload==='object'?{...payload,cameras:Array.isArray(payload.cameras)?payload.cameras:[],alerts:Array.isArray(payload.alerts)?payload.alerts:[],detections:Array.isArray(payload.detections)?payload.detections:[],counts:payload.counts&&typeof payload.counts==='object'?payload.counts:{total:0,unacknowledged:0,high:0,medium:0,low:0},pipeline:payload.pipeline&&typeof payload.pipeline==='object'?payload.pipeline:{raw_frames:0,detections:0}}:{session:null,cameras:[],alerts:[],detections:[],counts:{total:0,unacknowledged:0,high:0,medium:0,low:0},pipeline:{raw_frames:0,detections:0}}),uploadTestVideo:file=>upload('/test/feeds/upload',file),removeTestVideo:id=>req(`/test/assets/${id}`,{method:'DELETE'}),addTestFeed:(sessionId,body)=>req(`/test/sessions/${sessionId}/feeds`,{method:'POST',body:JSON.stringify(body)}),removeTestFeed:(sessionId,streamId)=>req(`/test/sessions/${sessionId}/feeds/${streamId}`,{method:'DELETE'}),createTestSession:body=>req('/test/sessions',{method:'POST',body:JSON.stringify(body)}),getActiveTestSession:()=>req('/test/sessions/active'),getTestStatus:id=>req(`/test/sessions/${id}/status`),getTestCameras:id=>req(`/test/sessions/${id}/cameras`),getTestResults:(id,p={})=>req(`/test/sessions/${id}/results?${new URLSearchParams(p)}`),closeTestSession:id=>req(`/test/sessions/${id}`,{method:'DELETE'}),seedDemoTestSession:()=>req('/test/demo/seed',{method:'POST'}),
 downloadTestResults:async id=>{const token=readAuthToken(),r=await fetch(`${BASE}/test/sessions/${id}/results/export`,{headers:token?{Authorization:`Bearer ${token}`}:{},credentials:'include'});if(!r.ok)throw new Error(`${r.status} ${r.statusText}`);return r.blob()},listEvidence:(p={},opts={})=>req('/evidence/?'+new URLSearchParams(p),opts),createEvidence:body=>req('/evidence/',{method:'POST',body:JSON.stringify(body)}),getEvidence:id=>req(`/evidence/${id}`),getEvidenceSignedToken:id=>req(`/evidence/${id}/signed-token`),downloadDetections:async()=>{const token=readAuthToken(),r=await fetch(`${BASE}/reports/detections?format=csv`,{headers:token?{Authorization:`Bearer ${token}`}:{},credentials:'include'});if(!r.ok)throw new Error(`${r.status} ${r.statusText}`);return r.blob()}
}
export const WS_URL=import.meta.env.VITE_WS_URL||`${window.location.protocol==='https:'?'wss:':'ws:'}//${window.location.host}/ws/alerts`
